#!/usr/bin/env python3
#
# Translate a python test to another language.
#
import sys
import argparse
import ast
import os.path
import csharpgen
from asttoirvisitor import AstToIrVisitor


def main():
    args = cmd_line_args()
    extension = os.path.splitext(args.output_file)[1]
    if extension != '.cs':
        raise Exception(f"Unsupported file extension '{extension}'")
    input_ast = parse_file(args.input_file)
    module = AstToIrVisitor().visit(input_ast)
    csharpgen.translate(module, args.output_file)


def cmd_line_args():
    parser = argparse.ArgumentParser(
        description="Translate python test to another language")
    parser.add_argument("input_file")
    parser.add_argument("output_file")
    return parser.parse_args()


def parse_file(file_name):
    with open(file_name, "r") as f:
        input_source = f.read()

    try:
        return ast.parse(input_source, file_name)
    except SyntaxError as syntaxError:
        sys.exit(f"ERROR: failed to parse '{file_name}': {syntaxError}")


if __name__ == "__main__":
    main()
