#!/usr/bin/env python3
#
# Translate a python test to another language.
#
import argparse
import os.path
import backend.csharp


def main():
    args = cmd_line_args()
    extension = os.path.splitext(args.output_file)[1]
    if extension != '.cs':
        raise Exception(f"Unsupported file extension '{extension}'")
    backend.csharp.translate(read_file(args.input_file), args.output_file)


def cmd_line_args():
    parser = argparse.ArgumentParser(
        description="Translate python test to another language")
    parser.add_argument("input_file")
    parser.add_argument("output_file")
    return parser.parse_args()


def read_file(file_name):
    with open(file_name, "r") as f:
        return f.read()


if __name__ == "__main__":
    main()
